language: shell
dist: trusty
sudo: required

before_script:
    # installing the newer docker-compose version to understand required env vars
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/1.25.0/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - cd docker
    - sudo docker network create OMS
    - export MYAEGEE_ENV=development
    - export PATH_OMS_MAILER=.
    - export SMTP_HOST=localhost
    - export SMTP_USER=admin@aegee.eu
    - export SMTP_PASSWORD=5ecr3t
    - sudo docker-compose -f docker-compose.yml -f docker-compose.dev.yml build

script:
    - sudo docker-compose -f docker-compose.yml -f docker-compose.dev.yml run oms-mailer env MIX_ENV=test mix coveralls
