language: shell
dist: trusty
sudo: required

services:
  - docker

before_script:
    - cd docker
    - sudo docker-compose -f docker-compose-secrets.yml -f docker-compose.yml build

script:
    - sudo docker-compose -f docker-compose-secrets.yml -f docker-compose.yml exec oms-mailer env MIX_ENV=test mix test
