orbs:
  slack: circleci/slack@3.4.1
version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && sudo dpkg -i erlang-solutions_2.0_all.deb
      - run: sudo apt-get update
      - run: sudo apt-get install elixir esl-erlang
      - run: MIX_ENV=test mix local.hex --force
      - run: MIX_ENV=test mix local.rebar --force
      - run: MIX_ENV=test mix deps.get
      - run: MIX_ENV=test mix coveralls
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker-compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml build --no-cache oms-mailer
  docker-build-and-push-mailer:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker build  --tag aegee/oms-mailer:$(node -p "require('./package.json').version") --tag aegee/oms-mailer:latest -f docker/oms-mailer/Dockerfile .
      - run: docker login --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
      - run: docker push aegee/oms-mailer:$(node -p "require('./package.json').version")
      - run: docker push aegee/oms-mailer:latest
      - slack/status:
          success_message: The Docker image for \`$CIRCLE_PROJECT_REPONAME\` with tags \`$(node -p "require('./package.json').version")\` and \`latest\` has been pushed to Dockerhub.
          failure_message: The Docker image for \`$CIRCLE_PROJECT_REPONAME\` build and push has failed.
  docker-build-and-push-agent:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker build  --tag aegee/oms-mail-transfer-agent:$(node -p "require('./package.json').version") --tag aegee/oms-mail-transfer-agent:latest -f docker/mail_transfer_agent/Dockerfile .
      - run: docker login --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
      - run: docker push aegee/oms-mail-transfer-agent:$(node -p "require('./package.json').version")
      - run: docker push aegee/oms-mail-transfer-agent:latest
      - slack/status:
          success_message: The Docker image for \`oms-mail-transfer-agent\` with tags \`$(node -p "require('./package.json').version")\` and \`latest\` has been pushed to Dockerhub.
          failure_message: The Docker image for \`oms-mail-transfer-agent\` build and push has failed.

workflows:
  version: 2
  test:
    jobs:
      - test
  build:
    jobs:
      - build
  docker-build-and-push-mailer:
    jobs:
      - docker-build-and-push-mailer:
          filters:
            branches:
              only: master
  docker-build-and-push-agent:
    jobs:
      - docker-build-and-push-agent:
          filters:
            branches:
              only: master
