version: '3.2'

services:
    oms-mailer:
        build:
            context: ./$PATH_OMS_MAILER/../
            dockerfile: ./docker/oms-mailer/Dockerfile
        expose:
            - "4000"
        environment:
            MIX_ENV: prod
        depends_on:
            - oms-mail-transfer-agent

    oms-mail-transfer-agent:
        build:
            context: ./$PATH_OMS_MAILER/mail_transfer_agent
            dockerfile: Dockerfile
        expose:
            - "25"
        secrets:
            - mail_password
            - mail_user
