version: "3.4"

services:
    mailer:
        build:
            context: ./${PATH_MAILER}/../
            dockerfile: ./docker/mailer/Dockerfile
            args: 
                MIX_ENV: development
        image: aegee/mailer:dev
        volumes:
            - /usr/src/myapp/deps

    mail-transfer-agent:
        build:
            context: ./${PATH_MAILER}/..
            dockerfile: docker/mail_transfer_agent/Dockerfile
        image: aegee/mail-transfer-agent:dev
