version: "3.4"

services:
    oms-mailer:
        restart: unless-stopped
        image: aegee/oms-mailer:latest
        expose:
            - "4000"
        environment:
            MIX_ENV: "${MYAEGEE_ENV}"
        depends_on:
            - oms-mail-transfer-agent
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:4000/healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        # Only exposing /healthcheck endpoint
        labels:
            - "traefik.backend=oms-mailer"
            - "traefik.port=4000"
            - "traefik.frontend.rule=Path:/services/oms-mailer/api/healthcheck;PathPrefixStrip:/services/oms-mailer/api"
            - "traefik.frontend.priority=110"
            - "traefik.enable=true"
        # cpu_count: 1
        # mem_limit: 900m

    oms-mail-transfer-agent:
        restart: always
        image: aegee/oms-mail-transfer-agent:latest
        expose:
            - "25"
        secrets:
            - mail_password
            - mail_user
        #healthcheck?
        # cpu_count: 1
        # mem_limit: 900m

networks:
    default:
        external:
            name: OMS
