version: "2.4"

services:
    oms-mailer:
        build:
            context: ./$PATH_OMS_MAILER/../
            dockerfile: ./docker/oms-mailer/Dockerfile
        image: aegee/oms-mailer:latest

    oms-mail-transfer-agent:
        build:
            context: ./$PATH_OMS_MAILER/mail_transfer_agent
            dockerfile: Dockerfile
        image: aegee/oms-mail-transfer-agent:latest
