version: '3.2'

services:
    oms-mailer:
        restart: unless-stopped
        build:
            context: ./$PATH_OMS_MAILER/../
            dockerfile: ./docker/oms-mailer/Dockerfile
        image: aegee/oms-mailer        
        expose:
            - 4000
        # environment:
        #     MIX_ENV: ${MIX_ENV}
        env_file: ./$PATH_OMS_MAILER/.env
        depends_on:
            - oms-mail-transfer-agent
        # no traefik labels here, because we do not want 
        # this API to be reachable from outside

    oms-mail-transfer-agent:
        restart: always
        build:
            context: ./$PATH_OMS_MAILER/mail_transfer_agent
            dockerfile: Dockerfile
        image: aegee/oms-mail-transfer-agent        
        expose:
            - 25
        secrets:
            - mail_password
            - mail_user

networks:
  default:
    external:
      name: OMS
